### PR TITLE
Docker support and Markdown README

### PR DESCRIPTION
**Pull request by nicopace**
This merge request adds Docker support, and updates README to reflect it.
Also moves README to markdown.

### CODE REVIEW

**Comment by ssinyagin** [comment]
Nico, I don't like this pull request in a number of ways:

1. Your version of README becomes unreadable as plain text. You know, the plain old text in a terminal :)

2. As you moved around the directory structure, and in your installation procedure you propose to copy files into /etc -- this way the link to this Git repository and its history is lost. As a result, you can't merge your working configuration with new updates on github.

So, I have to reject your PR. I would suggest that you maintain your own version, dedicated for Docker. I can place a link in my README to your repository when you're ready.

**Comment by nicopace** [comment]
Hi Stanislav,
Thanks for replying my pull request.
I would really like to make it so we can share the maintenance... I could do the Docker support while you do the other stuff.

So... in order to do that, would be great for me to get to a point were you agree on the pull request.

Would it be ok if:
1. we keep the README with the previous format? (Markdown is also plain text, but if you prefer the format you were using... it is ok for me)
2. leave the files were they were, and make the Dockerfile deal with it

What do you think?

**Comment by nicopace** [comment]
BTW on (2) loosing the history of a 29 commit repo is not that of a big deal... isn't it?
The structure proposed on this pull request seems more clean... although I understand that you can't clone it into the etc/freeswitch directory... but you shouldn't either because you should have to do adjustments to make it work for your setup... so you need to customize it.

Can you share your workflow? perhaps that way it would be easier to understand your decision.

Thanks!

**Comment by ssinyagin** [comment]
hi Nico,

in regards to README, it should be easily readable on a 80x24 terminal. Those &lt;pre&gt;&lt;code&gt;... tags are simply polluting the content, and not adding anything useful.

The workflow is very simple: you clone into /etc/freeswitch, then add your changes, commit and probably push them to another repo, and if the upstream repo has any updates, you can easily fetch and merge. So, having an extra step in copying the content into /etc/freeswitch looks like a degradation of service.

Why can't you have docker files in a separate repository, and instruct the user to do two clones? There's also a possibility for submodules that might be useful for you: https://git-scm.com/book/en/v2/Git-Tools-Submodules

My criteria is very simple: the changes should not break compatibility and should make as little as possible assumptions in regards to how this configuration would be used by the user. Actually with the use of submodules, the user can have /etc/freeswitch from their own repo, and still have Docker files from yours.

**Comment by nicopace** [comment]
Hi Stanislav,

Thanks for replying!

I get the 80x24 terminal... I can live with that.
The "pre code" allows the code blocks to appear as code blocks.
Another way is to add three aphostrophes and after that the language used... would that be ok for you?

Something like this:
```bash
echo "umask 0007" >>~/.profile 
umask 0007
sudo adduser jsmith freeswitch
sudo mkdir /etc/freeswitch
sudo chgrp freeswitch /etc/freeswitch
sudo chmod g+ws /etc/freeswitch
cd /etc/freeswitch
git init --shared=0660
git pull https://github.com/voxserv/freeswitch_conf_minimal.git master
```

We can add a Dockerfile that does exactly what you say.. fetching the code from repository... I really don't felt that it would be the best way to go (because it invalidates the cache from there on)... but it is cetainly simpler... we can go that way.

Let me know your thoughts about the README,.. that would make the code nicer at the GitHub level.

Regards

**Pull request closed without merging**
